### PR TITLE
Update gameconfig.xml - Increase ClothStore Limit

### PR DESCRIPTION
**Pull request by SoosyBoosy**
Increase ClothStore limit from 60 to 600 - fixes crashes with users who have a lot of addon peds cloth dictionaries

### CODE REVIEW

**Comment by ROK-JASON** [comment]
In my case, the problem occurs with EUP.
It may not load right away and the texture may be broken.
There is a phenomenon in which loading problems occur in EUP.
I've tried everything, but I hope the Gameconfig uploads quickly.

**Comment by successtheman** [comment]
These days I don't do much with GTA but back in 2020 I submitted a pull request that also increased clothstore poolsize from 60 to 600 to FiveM and it was eventually approved. Thought I would link this to show that it should be safe to make this change so it hopefully gets approved here too

https://github.com/citizenfx/fivem/pull/496

**Comment by pnwparksfan** [comment]
Testing this out in game and it seems good to me. You only changed the file in the `latest` folder though. For consistency I keep the current game version matched to the `latest` folder. Can you update the PR? Also, I think you removed the newline at the end of the file.

**Comment by SoosyBoosy** [comment]
sure i'll do it this week end

**Comment by SoosyBoosy** [comment]
sorry i forgot about this, going to work on it today

**Comment by SoosyBoosy** [comment]
should be good now, can you verify

**Comment by Michael21107** [comment]
@pnwparksfan

**Comment by pnwparksfan** [comment]
This change has been included in the latest version

**Pull request closed without merging**
